version: '2'
# NOTE: move this answer file up a directory so it'll work

services:

  dota-bot:
    image: dota-bot-image
    build: .
    ports:
      - "80:8888"
    volumes:
      - .:/app/
 
  mongo:
    image: mongo
    volumes:
        - './data:/data/db'
    ports:
        - 27017:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example